originalData:
  dataset_CT: ["allenai/c4", "realnewslike"]
  dataset_FT: ["universal_dependencies", "en_ewt"] # used in anywhere
  raw_CT: "/home/hyohyeongjang/2024SWELL/data_raw/ct_raw_v3" # used in anywhere
  raw_FT: "/home/hyohyeongjang/2024SWELL/data_raw/ft_raw_v3.pk" # used in anywhere
  raw_filter_original_CT: "/home/hyohyeongjang/2024SWELL/data_raw/ct_filter_original_v3.pk" # used in anywhere
  raw_filter_split_CT: "/home/hyohyeongjang/2024SWELL/data_raw/ct_filter_splitted_v3.pk" # used in anywhere
  raw_filter_FT: "/home/hyohyeongjang/2024SWELL/data_raw/ft_filter_v3.pk" # used in anywhere

dataStats: 
  bag_of_word_CT: "/home/hyohyeongjang/2024SWELL/meta/BOW_CT_v3.pk" # used in getWords
  bag_of_word_FT: "/home/hyohyeongjang/2024SWELL/meta/BOW_FT_v3.pk" # used in getWords
  cnt_pos_CT: "/home/hyohyeongjang/2024SWELL/meta/cnt_pos_CT_v3.pk" # used in getWords
  cnt_pos_FT: "/home/hyohyeongjang/2024SWELL/meta/cnt_pos_FT_v3.pk" # used in getWords
  file_wordStats_CT: "/home/hyohyeongjang/2024SWELL/meta/word_ct_v3.pk" # used in getWords
  file_wordStats_FT: "/home/hyohyeongjang/2024SWELL/meta/word_ft_v3.pk" # used in getWords
  uposToPenn: '{"ADJ": ["JJ", "JJR", "JJS"], "ADV": ["RB", "RBR", "RBS", "WRB"],
                "ADP": ["RP", "IN", "TO"],  "AUX": ["MD", "VB", "VBP", "VBG", "VBN", "VBD", "VBZ"], 
                "CCONJ": ["CC"], "DET": ["DT", "PDT", "WDT"], "INTJ": ["UH"],
                "NOUN": ["NN", "NNS"],  "NUM": ["CD"], "PART": ["TO", "RB"],  
                "PRON": ["PRP", "PRP$", "WP", "WP$"], "PROPN": ["NNP", "NNPS"],
                "PUNCT": ["``", "''", "-LRB-", "-RRB-", ",", ".", ":", "HYPH"],
                "SCONJ": ["IN"], "SYM": ["NFP", "#", "$", "SYM", "%"],  
                "VERB": ["VB", "VBP", "VBZ", "VBD", "VBG", "VBN"],  
                "X": ["FW", "LS", "XX", "ADD", "AFX", "GW"]}'
  pennToUpos: '{"JJ": "ADJ", "JJR": "ADJ", "JJS": "ADJ",
                "RB": "ADV", "RBR": "ADV", "RBS": "ADV", "WRB": "ADV", 
                "RP": "ADP", "IN": "ADP", "TO": "ADP", 
                "MD": "AUX", "VB": "AUX", "VBP": "AUX", 
                "VBG": "AUX",  "VBN": "AUX",  "VBD": "AUX",  "VBZ": "AUX",  
                "CC": "CCONJ", "DT": "DET", "PDT": "DET", "WDT": "DET",
                "UH": "INTJ", "NN": "NOUN", "NNS": "NOUN", "CD": "NUM",
                "PRP": "PRON", "PRP$": "PRON", "WP": "PRON", "WP$": "PRON",
                "NNP": "PROPN", "NNPS": "PROPN", 
                "``": "PUNCT", "''": "PUNCT", "-LRB-": "PUNCT", "-RRB-": "PUNCT",
                ",": "PUNCT", ".": "PUNCT", ":": "PUNCT", "HYPH": "PUNCT",
                "NFP": "SYM", "#": "SYM", "$": "SYM", "SYM": "SYM", "%": "SYM",
                "FW": "X", "LS": "X", "XX": "X", "ADD": "X", "AFX": "X", "GW": "X",}'
  idToLabel: '{0: "NOUN", 1: "PUNCT", 2: "PART", 3: "NUM", 4: "SYM", 5: "SCONJ",    
              6: "ADJ", 7: "ADP", 8: "DET", 9: "CCONJ", 10: "PROPN", 11: "PRON", 12: "X", 
              13: "UNK", 14: "ADV", 15: "INTJ", 16: "VERB", 17: "AUX"}'
  labelToId: "{'NOUN': '0','PUNCT': '1','PART': '2','NUM': '3','SYM': '4','SCONJ': '5',
              'ADJ': '6','ADP': '7','DET': '8','CCONJ': '9','PROPN': '10','PRON': '11',
              'X': '12','UNK': '13','ADV': '14','INTJ': '15','VERB': '16','AUX': '17'}"
  subwordPos_CT: "/home/hyohyeongjang/2024SWELL/meta/subwordPos_CT_v3.pk"
  subword_CT: "/home/hyohyeongjang/2024SWELL/meta/subword_CT_v3.pk"
  pos_freq_CT: "/home/hyohyeongjang/2024SWELL/meta/pos_freq_CT_v3.pk"
  pos_abund_CT:  "/home/hyohyeongjang/2024SWELL/meta/pos_abund_CT_v3.pk"
  scores_original_CT: "/home/hyohyeongjang/2024SWELL/scores/score_CT_original_{}_v3.pk" # used in getScores
  scores_masked_CT: "/home/hyohyeongjang/2024SWELL/scores/score_CT_mask_{}_v3.pk" # used in getScores
  checkpoint_pplModel: "meta-llama/Meta-Llama-3-8B-Instruct" # used in getScores
  num_cores: 40 # making dataset

contFiles:
  ratio: [0.25, 0.5, 0.75, 1.0]
  data_CT: "/home/hyohyeongjang/2024SWELL/data_CT/CT_{}_{}_{}_v3.pk" # used in getFiles
  data_FT: "/home/hyohyeongjang/2024SWELL/data_FT/FT_{}_{}_{}_v3.pk" # used in getFiles

contTrain:
  checkpoint_baseModel: "FacebookAI/roberta-base" # used in continualTrain
  checkpoint_CTModel: "/home/hyohyeongjang/2024SWELL/weights/CT/CT_{}_{}_{}" # used in continualTrain
  max_seq_len: 512
  batch_size: 64 # 64에 약 25000MiB(100%)
  do_RandomInitialize: False
  num_cores_train: 10

fineTune:
  checkpoint_FTModel: "/home/hyohyeongjang/2024SWELL/weights/FT/FT_{}_{}_{}_{}" # used in continualTrain

